[server default]
user=mhauser #用于远程连接MySQL所有节点的用户,需要有管理员的权限
password=Aa@123456
manager_workdir=/data/mastermha/app1/  #目录会自动生成,无需手动创建
manager_log=/data/mastermha/app1/manager.log
remote_workdir=/data/mastermha/app1/
ssh_user=root  #用于实现远程ssh基于KEY的连接,访问二进制日志
repl_user=repluser #主从复制的用户信息
repl_password=Aa@123456
ping_interval=1  #健康检查的时间间隔
master_ip_failover_script=/usr/local/bin/master_ip_failover  #切换VIP的perl脚本
report_script=/usr/local/bin/sendmail.sh #当执行报警脚本
check_repl_delay=0  #默认值为1,表示如果slave中从库落后主库relay log超过100M，主库不会选
择这个从库为新的master，因为这个从库进行恢复需要很长的时间.通过设置参数check_repl_delay=0，
mha触发主从切换时会忽略复制的延时，对于设置candidate_master=1的从库非常有用，这样确保这个从库
一定能成为最新的master
master_binlog_dir=/data/mysql/ #指定二进制日志存放的目录,mha4mysql-manager-0.58必须指
定,之前版本不需要指定
[server1]
hostname=192.168.237
candidate_master=1
[server2]
hostname=192.168.237
candidate_master=1 #设置为优先候选master，即使不是集群中事件最新的slave,也会优先当
master
[server3]
hostname=192.168.237
